<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://docs.google.com/forms/d/e/1FAIpQLSeNJ_P1mAmBwf15aSOAz94v_N1wtyS9vM3Fx327T3eJMdjUvw/formResponse');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "ifq&entry.216580841=\"反対\"&entry.469609971=\"反対\"&entry.1520536758=\"反対\"&submit=Submit");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

header("Access-Control-Allow-Origin: *");

echo "送信完了しました。";